---
layout:     post
title:      "Java中错误与异常机制 "
date:       2016-12-16 
categories: Java
tags: Java 异常机制
---

​         Java中出错的情况分两种：异常（Exception）和错误（Error）。我们可以通过下面这张图来理解Java中异常和错误体系。

![java中异常和错误体系](https://lukkyy.github.io/assets/java/basic/Throwable.png)	







错误和异常都继承于Throwable 父类

​         **Error（错误）**：一般是和java虚拟机相关的问题，比如内存溢出、系统崩溃，一般的开发人员无法解决这些错误。
​         **Exception（异常） **：异常主要是指程序的语法语义错误，是我们开发时常说的Bug，异常可以由开发者解决。Note：异常又分为checked异常（编译时异常）和**Runtime异常**（运行时异常）两种。RuntimeException包括我们很熟悉的 NullPointerException（空指针异常）、IndexOutOfBoundsException（索引越界）、ArithmeticException（算术异常，比如除零）



---

```java
在类实例化时运行	
static String str = "test";  //
static {                     //静态块
		System.out.println("hello");
	}	
```

#### 1. 错误

```
Java中常见的代码错误
private Student stu = new Student();
          属性        不能new自己的对象 
```



#### **2. 异常机制**

异常机制就是对可能出现的错误进行处理的机制：

五个关键字：try、catch、finally、throw、throws。

如果在写函数是遇到异常，使用try{} catch{}来捕获处理异常，异常对象的常用函数有：

```java
getMessage（）；返回该异常的详细描述字符
printStackTrace（）：将该异常的跟踪栈信息输出到标准错误输出。
printStackTrace（PrintStream s）：将该异常的跟踪栈信息输出到指定的输出流
getStackTrace（）：返回该异常的跟踪栈信息。
```

如果不想在出现异常的函数处理，用throw 或 throws 关键字把可能出现的异常抛给调用该函数的上级函数处理，谁调用改函数谁处理，也可以一直往上抛给JVM处理（不建议）。

```java
错误和异常的例子：
public class Student {
	String name;
	int score;
	public void setScore(int score) throws ScoreException {//抛出异常用throws
		if(score < 0) {	
			throw new ScoreException("成绩不能为负数"); //抛出具体的异常，用throw
		}
		this.score = score;
	}
	public int study() throws ScoreException {
		try {                         //try正确才运行后面内容，否则直接跳转到catch里
			if(name.equals("张三")) {
			}
			score++;
			return score;
		} catch (Exception ex) {        //处理Exception后，抛出新的异常
			ex.printStackTrace(); 
//			throw new ScoreException(ex.getMessage());
		} catch (Throwable t) {         //catch的内容可以注释，直接运行finally
			t.printStackTrace();
		} finally {         //不管出没出错，finally代码始终被执行，可用来回收资源
			System.out.println("finally");
		}
		System.out.println("学习中。。。");  //若错误异常被抛出，下面的代码不执行
		return score;
	}

	public static void main(String[] args) throws ScoreException {
		Student stu = new Student();
		stu.name = "test";
		int score = stu.study();
		System.out.println("score="+score);
//		try {
//			stu.setScore(-10);
//		} catch (ScoreException e) {	
//			e.printStackTrace();
//		}
		try {
			new Student().study();
		} catch(Error err) {
			System.out.println(err.toString());//打印错误信息
       		err.printStackTrace();   //打印错误堆栈，可输出到文件
		}
	}
///另外一个类    
    public class ScoreException extends Exception {
	public ScoreException(String str) {
		super(str);
	}
}
}

```

